In [ ]:
# Practical : 6
# Title : Linear transformation
# Name: Snehal Gawade
# PRN:2401208025

In [1]:
#To find the kernel, range, null space, and perform linear transformations

In [1]:
import numpy as np
from sympy import Matrix

# Define a matrix for the linear transformation
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Convert the matrix to a symbolic matrix for symbolic computations
A_symbolic = Matrix(A)

# Find the kernel (null space) using SVD
_, s, vh = np.linalg.svd(A)
tolerance = 1e-10  # Threshold for considering singular values as zero
null_space = vh[np.abs(s) < tolerance]

# Find the range (column space) dimension using NumPy
range_dimension = np.linalg.matrix_rank(A)

# Perform a linear transformation on a vector using NumPy
vector_to_transform = np.array([1, 2, 3])
transformed_vector = np.dot(A, vector_to_transform)

# Print the results
print("Original Matrix:")
print(A)

print("\nNull Space (Kernel):")
if null_space.size == 0:
    print("No null space (kernel is trivial).")
else:
    print(null_space)

print("\nRange (Column Space) Dimension:")
print(range_dimension)

print("\nLinear Transformation:")
print("Original Vector:", vector_to_transform)
print("Transformed Vector:", transformed_vector)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Null Space (Kernel):
[[-0.40824829  0.81649658 -0.40824829]]

Range (Column Space) Dimension:
2

Linear Transformation:
Original Vector: [1 2 3]
Transformed Vector: [14 32 50]


In [3]:
# Find orthogonal projection
import numpy as np

def orthogonal_projection(vector, subspace_vectors):
    subspace_matrix = np.array(subspace_vectors).T
    projection_matrix = np.dot(subspace_matrix, np.linalg.inv(np.dot(subspace_matrix.T, subspace_matrix)))
    projection = np.dot(projection_matrix, vector)
    return projection

# Example: Find the orthogonal projection of [1, 2, 3] onto the subspace spanned by v1, v2, v3
v1 = np.array([1, 1, 0])
v2 = np.array([0, 1, 1])
v3 = np.array([0, 0, 1])

vector_to_project = np.array([1, 2, 3])
projection_result = orthogonal_projection(vector_to_project, [v1, v2, v3])

print("Vector to Project:")
print(vector_to_project)

print("\nOrthogonal Projection:")
print(projection_result)


Vector to Project:
[1 2 3]

Orthogonal Projection:
[ 2. -1.  3.]
