In [1]:
#Q1 Check the following set of vectors are linearly dependent or independent

In [2]:
import numpy as np
A=np.array([[1,0,2],[2,1,0],[3,2,1]])
rank=np.linalg.matrix_rank(A)
col=A.shape[-1]
if rank==col:
    print("Independent")
else:
    print("Dependent")

Independent


In [3]:
#Q2 Check wheather the given set of vectors forms a basis or not ,get input from users

In [13]:
import numpy as np
v1=[]
v2=[]
v3=[]
for i in range(1,4):
    a=int(input("Enter the number"))
    v1.append(a)
for i in range(1,4):
    a=int(input("Enter the number"))
    v2.append(a)
for i in range(1,4):
    a=int(input("Enter the number"))
    v3.append(a)

print(v1)
print(v2)
print(v3)

A=np.array([[v1,v2,v3]])
print(A)

Enter the number 1
Enter the number 4
Enter the number 3
Enter the number 6
Enter the number 8
Enter the number 2
Enter the number 9
Enter the number 5
Enter the number 3


[1, 4, 3]
[6, 8, 2]
[9, 5, 3]
[[[1 4 3]
  [6 8 2]
  [9 5 3]]]


In [15]:
det=np.linalg.det(A)
print(det)
rank=np.linalg.matrix_rank(A)
print(rank)
col=A.shape[1]
print(col)
if(det!=0):
    print("Span\n")
    if(rank==col):
        print("Linearly Independent\n")
        print("Basis")
    else:
        print("Linearly Dependent\n")
else:
        print("Not Basis")


[-112.]
[3]
3
Span

Linearly Independent

Basis


In [17]:
import numpy as np
A=np.array([[1,2,3],[0,1,4],[5,6,0]])
det=np.linalg.det(A)
print(det)
rank=np.linalg.matrix_rank(A)
print(rank)
col=A.shape[1]
print(col)
if(det!=0):
    print("Span\n")
    if(rank==col):
        print("Linearly Independent\n")
        print("Basis")
else:
        print("Not Basis")

0.9999999999999987
3
3
Span

Linearly Independent

Basis
