In [1]:
import numpy as np

* Q1. Find the Eigen Value & EigenVector of the Folloing Matrix

In [5]:
A=np.array([[4,2,-2],[-5,3,2],[2,4,1]])
print(np.linalg.eigh(A))
eigenvalues,eigenvectors = np.linalg.eig(A)
print("Eigenvalues:",eigenvalues)
print("Eigenvector:",eigenvectors)

EighResult(eigenvalues=array([-4.79071104,  4.02386408,  8.76684696]), eigenvectors=array([[-0.49358016, -0.5555655 , -0.669123  ],
       [-0.62649221, -0.30651401,  0.71662868],
       [ 0.60322975, -0.77291405,  0.19676823]]))
Eigenvalues: [1.5+2.78388218j 1.5-2.78388218j 5. +0.j        ]
Eigenvector: [[ 4.77889504e-01+0.20467509j  4.77889504e-01-0.20467509j
   9.99257961e-17+0.j        ]
 [-1.47042924e-01+0.40935018j -1.47042924e-01-0.40935018j
   7.07106781e-01+0.j        ]
 [ 7.35214622e-01+0.j          7.35214622e-01-0.j
   7.07106781e-01+0.j        ]]


In [3]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
eigenvalues, eigenvectors = np.linalg.eig(A)

# Creating a diagonal matrix using eigenvalues
D = np.diag(eigenvalues)

# Finding the inverse of the eigenvector matrix
P = np.linalg.inv(eigenvectors)

# Diagonalizing matrix A
diagonalized_A = np.dot(np.dot(P, A), eigenvectors)

print("Diagonalized Matrix A:\n", diagonalized_A)


Diagonalized Matrix A:
 [[ 1.61168440e+01 -1.59005022e-15  6.34993565e-16]
 [ 5.35184690e-16 -1.11684397e+00  2.31510743e-16]
 [ 3.45615948e-15 -5.08144199e-16 -1.81298661e-16]]


* Q3. Write code for Matrix is Diagonalized or not

In [4]:
A=np.array([[6,-2,2],[-2,3,-1],[2,-1,3]])
print(np.linalg.eigh(A))
eigenvalues,eigenvectors = np.linalg.eig(A)
if len(eigenvalues)==len(np.unique(eigenvalues)):
    print("\nMatrix is Diagonalize")
else:
     print("\nMatrix is Not Diagonalize")


EighResult(eigenvalues=array([2., 2., 8.]), eigenvectors=array([[ 0.57735027,  0.        , -0.81649658],
       [ 0.57735027,  0.70710678,  0.40824829],
       [-0.57735027,  0.70710678, -0.40824829]]))

Matrix is Diagonalize
