In [1]:
# Step 1: Compute SVD
import numpy as np

A = np.array([[4, 11], [8, 7], [1, 8]])

In [2]:
U, S, VT = np.linalg.svd(A)
#Step 2: Result of SVD
print("\n U (Left Singular Matrix):")
print(U)
print("\n S (Singular Values):")
print(S)
print("\n VT (Transpose of Right Singular Matrix):")
print(VT)


 U (Left Singular Matrix):
[[ 0.68183627 -0.29903226 -0.66759195]
 [ 0.58106096  0.7758056   0.24595493]
 [ 0.44437312 -0.55561261  0.70272837]]

 S (Singular Values):
[17.02495141  5.01508021]

 VT (Transpose of Right Singular Matrix):
[[ 0.45933793  0.8882616 ]
 [ 0.8882616  -0.45933793]]


In [3]:
# Step 3: Dimensionality Reduction
k = 1  # Number of dimensions to keep
reduced_A = np.dot(U[:, :k], np.dot(np.diag(S[:k]), VT[:k, :]))
print("Reduced A (2D representation):")
print(reduced_A)

Reduced A (2D representation):
[[ 5.33209996 10.31114434]
 [ 4.54401632  8.78715862]
 [ 3.47508925  6.7200816 ]]


In [4]:
# Perform dimensionality reduction and reconstruction
reduced_U = U[:, :k]
reduced_S = np.diag(S[:k])
reduced_VT = VT[:k, :]
reconstructed_A = np.dot(reduced_U, np.dot(reduced_S, reduced_VT))
print("reduced_A:",reduced_U)
print("reduced_S:",reduced_S)
print("reduced_VT:",reduced_VT)

print("Original A:",A)
print("\nReconstructed A (k =", k, "):")
print(reconstructed_A)


reduced_A: [[0.68183627]
 [0.58106096]
 [0.44437312]]
reduced_S: [[17.02495141]]
reduced_VT: [[0.45933793 0.8882616 ]]
Original A: [[ 4 11]
 [ 8  7]
 [ 1  8]]

Reconstructed A (k = 1 ):
[[ 5.33209996 10.31114434]
 [ 4.54401632  8.78715862]
 [ 3.47508925  6.7200816 ]]
